name: Pipelina CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: build_ecr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::897074276729:role/GitHubActionsRepoApp
          aws-region: us-east-2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Amazon ECR Login
        uses: aws-actions/amazon-ecr-login@v2.0.2

      - name: Build, tag e push
        run: |
          docker build -t meu-website:v1.0 .
          docker tag meu-website:v1.0 897074276729.dkr.ecr.us-east-2.amazonaws.com/ecr-site-prod:v1.0
          docker push 897074276729.dkr.ecr.us-east-2.amazonaws.com/ecr-site-prod:v1.0

  job2:
    name: deploy_ec2
    needs: job1
    runs-on: ubuntu-latest

    env:
      PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}

    steps:
      - name: Deploy EC2 ssh
        run: |
          echo "$INSTANCE_KEY" > website-key.pem
          chmod 400 website-key.pem

          ssh -o StrictHostKeyChecking=no -i website-key.pem ec2-user@${PUBLIC_IP} << EOF
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 897074276729.dkr.ecr.us-east-2.amazonaws.com
            docker pull 897074276729.dkr.ecr.us-east-2.amazonaws.com/ecr-site-prod:v1.0
            docker stop site || true
            docker rm site || true
            docker run -d -p 80:80 --name meu-website 897074276729.dkr.ecr.us-east-2.amazonaws.com/ecr-site-prod:v1.0
            docker ps
          EOF

          rm website-key.pem